version: "3"

services:
  mosquitto:
    container_name: mqtt-container
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt-network

  express-server:
    container_name: express-server
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 8080:8080
    networks:
      - mqtt-network
    depends_on:
      - mosquitto

networks:
  mqtt-network:
    driver: bridge
