version: "3"

services:
  mosquitto:
    container_name: mqtt-container
    build:
      context: mosquitto
      dockerfile: Dockerfile
    environment:
      - MOSQUITTO_USERNAME=alim
      - MOSQUITTO_PASSWORD=a111111
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - mqtt-network

  express-server:
    container_name: express-server
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 8000:8000
    networks:
      - mqtt-network
    depends_on:
      - mosquitto

networks:
  mqtt-network:
    driver: bridge
